config/routes.rb
Wap::Application.routes.draw do

  namespace :admin do
    resources :photos
    resources :mobile_types
    resources :software_types
    resources :softwares
    resources :downfiles
    
    match 'upload' => 'upload_resource#index'
   
  end
  
  root :to => 'wap#index'
  match '/admin' => 'admin/home#index'

  match 'software/:id' => 'wap#show'
  match 'softwares/:id' => 'wap#more'
  
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
end

app/controllers/admin/software_types_controller.rb
class Admin::SoftwareTypesController < Admin::AdminController
  # GET /software_types
  # GET /software_types.xml
  def index
    @software_types = SoftwareType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @software_types }
    end
  end

  # GET /software_types/1
  # GET /software_types/1.xml
  def show
    @software_type = SoftwareType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @software_type }
    end
  end

  # GET /software_types/new
  # GET /software_types/new.xml
  def new
    @software_type = SoftwareType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @software_type }
    end
  end

  # GET /software_types/1/edit
  def edit
    @software_type = SoftwareType.find(params[:id])
  end

  # POST /software_types
  # POST /software_types.xml
  def create
    @software_type = SoftwareType.new(params[:software_type])

    respond_to do |format|
      if @software_type.save
        format.html { redirect_to( admin_software_type_path(@software_type), :notice => 'Software type was successfully created.') }
        format.xml  { render :xml => @software_type, :status => :created, :location => @software_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @software_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /software_types/1
  # PUT /software_types/1.xml
  def update
    @software_type = SoftwareType.find(params[:id])

    respond_to do |format|
      if @software_type.update_attributes(params[:software_type])
        format.html { redirect_to(admin_software_type_path(@software_type), :notice => 'Software type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @software_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /software_types/1
  # DELETE /software_types/1.xml
  def destroy
    @software_type = SoftwareType.find(params[:id])
    @software_type.destroy

    respond_to do |format|
      format.html { redirect_to(admin_software_types_path) }
      format.xml  { head :ok }
    end
  end
end

app/views/admin/software_types/_form.html.erb
<%= form_for([:admin, @software_type]) do |f| %>
  <% if @software_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software_type.errors.count, "error") %> prohibited this software_type from being saved:</h2>

      <ul>
      <% @software_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/software_types/edit.html.erb
<h1>Editing software_type</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_software_type_path(@software_type) %> |
<%= link_to 'Back', admin_software_types_path %>

app/views/admin/software_types/index.html.erb
<h1>Listing software_types</h1>

<table>
  <tr>
    <th>ID</th>
    <th>分类</th>
    <th>标题</th>
    <th>状态</th>
    <th>操作</th>
  </tr>

<% @software_types.each do |software_type| %>
  <tr>
    <td><%= software_type.id %></td>
   <td><%= software_type.parent.title if software_type.parent %></td>
    <td><%= software_type.title %></td>
    <td><%= software_type.status %></td>
    <td>
      <%= link_to '显示', admin_software_type_path(software_type) %> |
      <%= link_to '修改', edit_admin_software_type_path(software_type) %> |
      <%= link_to '删除', admin_software_type_path(software_type), :confirm => '确认删除吗？', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '添加新分类', new_admin_software_type_path %>

app/views/admin/software_types/new.html.erb
<h1>New software_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_software_types_path %>

app/views/admin/software_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @software_type.title %>
</p>

<p>
  <b>Status:</b>
  <%= @software_type.status %>
</p>


<%= link_to 'Edit', edit_admin_software_type_path(@software_type) %> |
<%= link_to 'Back', admin_software_types_path %>